version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  nextjs:
    build: ./nextjs
    volumes:
      - ./nextjs/frontend:/frontend
    ports:
      - "3000:3000"
    tty: true

